package net.rk.thingamajigs.datagen;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import net.neoforged.neoforge.common.data.SoundDefinition;
import net.neoforged.neoforge.common.data.SoundDefinitionsProvider;
import net.rk.thingamajigs.Thingamajigs;
import net.rk.thingamajigs.xtras.TSoundEvent;

public class TSound extends SoundDefinitionsProvider {
    public TSound(PackOutput output, ExistingFileHelper helper) {
        super(output, Thingamajigs.MODID, helper);
    }

    @Override
    public void registerSounds() {
        // alarm sound defs
        this.add(TSoundEvent.HORN.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/alarms/horn")
                                .volume(0.75f)
                                .pitch(1.0f)
                                .attenuationDistance(16)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.horn"));
        this.add(TSoundEvent.CODE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/alarms/code")
                                .volume(0.95f)
                                .pitch(1.0f)
                                .attenuationDistance(16)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.code"));
        this.add(TSoundEvent.BEEP.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/alarms/beep")
                                .volume(0.85f)
                                .pitch(1.0f)
                                .attenuationDistance(16)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.beep"));
        this.add(TSoundEvent.YODELER.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/alarms/yodeler")
                                .volume(0.7f)
                                .pitch(1.0f)
                                .attenuationDistance(16)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.yodeler"));

        // doorbell sound defs
        this.add(TSoundEvent.OLD.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/doorbells/old")
                                .volume(0.9f)
                                .pitch(1.0f)
                                .attenuationDistance(8)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.old"));
        this.add(TSoundEvent.ELECTRONIC.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/doorbells/electronic")
                                .volume(0.9f)
                                .pitch(1.0f)
                                .attenuationDistance(8)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.doorbell"));
        this.add(TSoundEvent.METALLIC.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/doorbells/metallic")
                                .volume(0.9f)
                                .pitch(1.0f)
                                .attenuationDistance(8)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.doorbell"));
        this.add(TSoundEvent.PLUCK.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/doorbells/pluck")
                                .volume(0.9f)
                                .pitch(1.0f)
                                .attenuationDistance(8)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.doorbell"));

        // poop sound defs
        this.add(TSoundEvent.POOP.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/poop_block/poop")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                ).subtitle("thingamajigs.subtitle.poop"));
        this.add(TSoundEvent.POOP_BREAK.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/poop_block/poop_break")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                ).subtitle("thingamajigs.subtitle.poop_break"));
        this.add(TSoundEvent.POOP_HIT.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/poop_block/poop_hit")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                ).subtitle("thingamajigs.subtitle.poop_hit"));
        this.add(TSoundEvent.POOP_STEP.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/poop_block/poop_step")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                ).subtitle("thingamajigs.subtitle.poop_step"));
        this.add(TSoundEvent.LARGE_POOP.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:item/large_poop")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                ).subtitle("thingamajigs.subtitle.large_poop"));

        // misc multipurpose sound defs
        this.add(TSoundEvent.AIR.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/air")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.air"));
        this.add(TSoundEvent.WATER_NOISE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/water_noise")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.water_noise"));
        this.add(TSoundEvent.POP.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/pop")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.pop"));
        this.add(TSoundEvent.ERROR.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:error")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.error"));
        this.add(TSoundEvent.SQUEAK.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/squeak")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.squeak"));
        this.add(TSoundEvent.PLASTIC_SHUFFLING.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/plastic_shuffling")
                                .volume(0.97f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.plastic_shuffling"));

        // tv sound defs
        this.add(TSoundEvent.STATIC.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/tv/static")
                                .volume(0.9f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.static"));

        // phone sound defs
        this.add(TSoundEvent.MOBILE_BEEP.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/mobile_beep")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_ZERO.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_zero")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_ONE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_one")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_TWO.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_two")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_THREE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_three")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_FOUR.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_four")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_FIVE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_five")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_SIX.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_six")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_SEVEN.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_seven")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_EIGHT.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_eight")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_NINE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_nine")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_POUND.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_pound")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));
        this.add(TSoundEvent.MOBILE_STAR.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/phone/mobile_star")
                                .volume(0.55f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.mobile_beep"));

        this.add(TSoundEvent.PHONE_BIRDS_PERHAPS.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/numbers/birds_perhaps")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .attenuationDistance(6)
                ).subtitle("thingamajigs.subtitle.birds_perhaps"));
        this.add(TSoundEvent.PHONE_NO_SERVICE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/numbers/no_service")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .attenuationDistance(6)
                ).subtitle("thingamajigs.subtitle.no_service"));
        this.add(TSoundEvent.PHONE_NOT_A_NUMBER.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/numbers/not_a_number")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .attenuationDistance(6)
                ).subtitle("thingamajigs.subtitle.not_a_number"));
        this.add(TSoundEvent.PHONE_SONG_MAYBE.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/numbers/song_maybe")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .attenuationDistance(6)
                ).subtitle("thingamajigs.subtitle.song_maybe"));

        // instrument sound defs
        this.add(TSoundEvent.KICK_DRUM.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/kick")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.kick"));
        this.add(TSoundEvent.SNARE_DRUM.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/snare")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.snare"));
        this.add(TSoundEvent.TOM_DRUM.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/tom")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.tom"));
        this.add(TSoundEvent.FLOOR_TOM_DRUM.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/floor_tom")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.floor_tom"));
        this.add(TSoundEvent.HIHAT.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/hihat")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.hihat"));
        this.add(TSoundEvent.CRASH_CYMBAL.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/crash")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.crash"));
        this.add(TSoundEvent.CONGA.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/conga")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.conga"));
        this.add(TSoundEvent.BONGO.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument/bongo")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                                .preload(true)
                                .attenuationDistance(10)
                ).subtitle("thingamajigs.subtitle.instrument.bongo"));
        // instrument block sound defs
        this.add(TSoundEvent.METALLIC_HIT.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument_block/metallic_hit")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.metallic_hit"));
        this.add(TSoundEvent.NATURAL_HIT.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument_block/natural_hit")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.natural_hit"));
        this.add(TSoundEvent.PAPER_HIT.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument_block/paper_hit")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.paper_hit"));
        this.add(TSoundEvent.RATTLE_HIT.get(),
                SoundDefinition.definition().with(
                        sound("thingamajigs:block/instrument_block/rattle_hit")
                                .volume(1.0f)
                                .pitch(1.0f)
                                .stream(false)
                ).subtitle("thingamajigs.subtitle.rattle_hit"));
    }
}
